apiVersion: guard.3istor.com/v1alpha1
kind: OffhoursSchedule
metadata:
  name: qcm-schedule
  namespace: qcm
spec:
  targetRef:
    name: qcm
  sleepAt: "37 8 * * *" 
  wakeAt: "40 8 * * *" 
  timezone: "Europe/Paris"