apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "offhours-guard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "offhours-guard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "offhours-guard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "offhours-guard.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "offhours-guard.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-ui
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}