apiVersion: v1
kind: Service
metadata:
  name: {{ include "offhours-guard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "offhours-guard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-ui
      port: {{ .Values.service.port }}
      targetPort: http-ui
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "offhours-guard.selectorLabels" . | nindent 4 }}